# Generated by Django 3.1.2 on 2021-05-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_monitor', '0004_auto_20210423_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(default='disponible', max_length=100),
        ),
    ]
