# Generated by Django 3.1.2 on 2021-05-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_monitor', '0005_auto_20210518_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='neveraproductdetail',
            name='color_tone',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='connectivity_options',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='contact_phone_installation',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='dimension_cm_deepening',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='dimension_cm_height',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='dimension_cm_width',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='door_type_nevecon',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='element_included',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='functional_duality',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='line_model_reference',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='maker_warranty',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='product_design',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
    ]
