# Generated by Django 3.1.2 on 2021-06-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_monitor', '0006_auto_20210525_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='neveraproductdetail',
            old_name='litre_capacity',
            new_name='brute_total_capacity',
        ),
        migrations.RenameField(
            model_name='neveraproductdetail',
            old_name='net_litre_capacity',
            new_name='net_freezer_capacity',
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='net_refrigerator_capacity',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
        migrations.AddField(
            model_name='neveraproductdetail',
            name='net_total_capacity',
            field=models.CharField(default='NO DATA', max_length=500),
        ),
    ]
