# Generated by Django 3.1.2 on 2021-07-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout_monitor', '0008_neveraproductdetail_all_dimensions_cm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neveraproductdetail',
            name='brute_total_capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='neveraproductdetail',
            name='net_freezer_capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='neveraproductdetail',
            name='net_refrigerator_capacity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='neveraproductdetail',
            name='net_total_capacity',
            field=models.FloatField(default=0.0),
        ),
    ]
